Fixed problem with call to FeatureEarleyChartParse that required an explicit import statement Added doctest section to test for this.
return FeatureEarleyChartParse(self.earley_grammar(),
NameError: global name 'FeatureEarleyChartParse' is not defined


svn/trunk/nltk@4162